// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpt2Nr9AoRG0ZXDC3fbs7X5XnrNzKGa3A',
    appId: '1:854723632123:web:641e79088e898ba40d895e',
    messagingSenderId: '854723632123',
    projectId: 'silvernest-apartments',
    authDomain: 'silvernest-apartments.firebaseapp.com',
    databaseURL: 'https://silvernest-apartments-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'silvernest-apartments.firebasestorage.app',
    measurementId: 'G-C3NJVR939B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4dA3W1m1sS2uoTV_nChARJXHK6l1m6rY',
    appId: '1:854723632123:android:ac7aa8146517346b0d895e',
    messagingSenderId: '854723632123',
    projectId: 'silvernest-apartments',
    databaseURL: 'https://silvernest-apartments-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'silvernest-apartments.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYO6QcirrnjyXWgPpjb2KA48zJLFH8Ppk',
    appId: '1:854723632123:ios:2b5b4ef57c897c950d895e',
    messagingSenderId: '854723632123',
    projectId: 'silvernest-apartments',
    databaseURL: 'https://silvernest-apartments-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'silvernest-apartments.firebasestorage.app',
    iosBundleId: 'com.example.silverNest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYO6QcirrnjyXWgPpjb2KA48zJLFH8Ppk',
    appId: '1:854723632123:ios:2b5b4ef57c897c950d895e',
    messagingSenderId: '854723632123',
    projectId: 'silvernest-apartments',
    databaseURL: 'https://silvernest-apartments-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'silvernest-apartments.firebasestorage.app',
    iosBundleId: 'com.example.silverNest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpt2Nr9AoRG0ZXDC3fbs7X5XnrNzKGa3A',
    appId: '1:854723632123:web:4dc9fab04e0e8f5b0d895e',
    messagingSenderId: '854723632123',
    projectId: 'silvernest-apartments',
    authDomain: 'silvernest-apartments.firebaseapp.com',
    databaseURL: 'https://silvernest-apartments-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'silvernest-apartments.firebasestorage.app',
    measurementId: 'G-VJKMRT045B',
  );
}
